### PR TITLE
Try out static instance tracer field [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
@creamsoup @ejona86 @zhangkun83 Looking for your thoughts on this

Trying out a new API for perfmark.   This makes the PerfMark class not a collection of static methods, but a singleton holder of itself. There are some benefits to this:

1.  The `Impl` class is gone, shrinking the api jar and method count.   Looks like maybe 1KB.
2.  It is much harder for outside classes to extend `Impl`.  I originally didnt want to leak the unpacking / packing methods in Impl to the out side, but there wasnt a good way to do so.   Making those methods static would have made it possible for outsiders to subclass it and call the static methods directly.  PerfMark and Impl are rolled in together now.
3.  It is now impossible for subclasses of Impl (now PerfMark) to be instantiated.  The ctor now ensures that only clinit can construct the instance, 
4.  Access is now through the `tracer()` static method.  I kind of like this because it can be statically imported, without having to litter the class name `PerfMark` everywhere.

In terms of making this work with the existing classes without break api, I was thinking of maybe making a sep package called `perfmark-tracer` at `io.perfmark.trace`, and maybe naming the class Tracer.    The real impl would like inside perfmark-impl just like API does, so existing calls sites would still work.

Thoughts?

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
Some initial benchmarks:

```
Before:
Benchmark                   (enabled)  Mode  Cnt   Score   Error  Units
EnabledBenchmark.createTag       true  avgt    5   5.512 ± 0.230  ns/op
EnabledBenchmark.createTag      false  avgt    5   2.714 ± 0.018  ns/op
EnabledBenchmark.event           true  avgt    5  32.612 ± 0.559  ns/op
EnabledBenchmark.event          false  avgt    5   0.610 ± 0.008  ns/op
EnabledBenchmark.link            true  avgt    5  12.487 ± 0.200  ns/op
EnabledBenchmark.link           false  avgt    5   0.602 ± 0.005  ns/op
EnabledBenchmark.startStop       true  avgt    5  60.258 ± 1.927  ns/op
EnabledBenchmark.startStop      false  avgt    5   0.601 ± 0.007  ns/op

After:
Benchmark                   (enabled)  Mode  Cnt   Score   Error  Units
EnabledBenchmark.createTag       true  avgt    5   5.695 ± 0.548  ns/op
EnabledBenchmark.createTag      false  avgt    5   3.000 ± 0.045  ns/op
EnabledBenchmark.event           true  avgt    5  34.924 ± 1.461  ns/op
EnabledBenchmark.event          false  avgt    5   0.619 ± 0.005  ns/op
EnabledBenchmark.link            true  avgt    5  12.901 ± 0.371  ns/op
EnabledBenchmark.link           false  avgt    5   0.629 ± 0.004  ns/op
EnabledBenchmark.startStop       true  avgt    5  64.067 ± 0.757  ns/op
EnabledBenchmark.startStop      false  avgt    5   0.601 ± 0.011  ns/op

```

**Comment by ejona86** [comment]
We are reading the benchmarks as "no change?" The 4µs increase is noticable, but there shouldn't be any difference so I'm okay if we're claiming that is noise.

1. We don't expect any improvement for Android, though, right? Since things should already be inlined. Or were the methods too large to be inlined by default?
2. This doesn't seem so much about extending but hiding internals. The new approach is now leaking the internals to users more directly as noise, as they will be using the PerfMark class already and protected methods are displayed lots of places. Maybe we can put them as static methods in a protected PerfMark.Impl class? (Or call it Unsafe to mirror Netty; whatever.)
3. I'm not quite sure I see the value. But it doesn't seem to hurt anything. It seems this was mostly the case already, except for reflection or doing a hack of creating a class in the io.perfmark package.
4. I don't see how `PerfMark.startTask();` is any more littered than `tracer().startTask();`. It's even same number of letters and same number of shift-keys. I prefer PerfMark since it is much more informative when reading (there's lots of different types of tracers). But I'm not bothered with doing `PerfMark.tracer()...`; I just don't see the claimed advantage

Concerning `io.perfmark.trace`, are you saying that there would be another artifact for this new API and we'd stop using the current one? If `Tracer` is the new name then code would always be encouraged to have the static import for `tracer()`... That seems too generic of a name to be considered a net win. But we could bikeshed over that.

So (2) I understand, but the other benefits I don't see. I see the benefit in (2), but I'm not sure it is worth the change. I don't feel the need to bend over backwards to save a user from themselves and I don't feel like this will provide any real benefit to users. I can't figure out what someone would gain by extending Impl to get at the pack/unpack. If that's a strong concern, I might want to think more about alternatives, but I do accept that many of the normal tricks incur costs.

**Comment by carl-mastrangelo** [comment]
@ejona86 thanks for the reply.  I am probably going to abandon this, the original reason was to avoid the static function call and avoid one level of inlining.   (In addition to shrinking binary size for android).

**Comment by ejona86** [comment]
Oh, one level of inlining... That would be an additional benefit.

What is the problem with a static function call? Isn't the only problem the visibility of the method?

**Comment by carl-mastrangelo** [comment]
@ejona86 There's another growing concern that Is hard to work into the static function model:  working with java 8 types for Lambdas.   I have run into problems where I would really like to defer calculation of the Tag, or Task name, and the current Java6 targeted API makes that hard.    I wanted to be able to expose tracing calls that accept lambdas.    If the tracer was an object, it could be cast to a subtype that is java8 specific and expose the methods, leaving `PerfMark` as the super class and only having the Java6 methods.


Having a separate top level tracer type would be a little ugly IMO, (such as `PerfMark8`) with all the static methods, and would look ugly.      I'm trying to figure out a way to expose the advanced tracer calls without breaking Android.  Any ideas here would be welcome.

One more thing:   Android does allow  desugaring lambdas, which means PerfMark could support it, but Android /does not/ allow using any of the library types (like `Supplier`).    PerfMark can bundle this type to allow callers to pass in lambdas, but it would bloat the binary, and not be very java 8 idiomatic.   Again, Looking for ideas on how to support Java8 without hurting android.

**Pull request closed without merging**
